### ISSUE TITLE
Метод Load в TaskManager

### ISSUE THREAD

**Issue by TurBinX** [TelurXS/TaskSystem#1]
По какой-то причине вылезает ошибка при попытке загрузить данные из .json файла

**Comment by NicoleHolic** [comment]
![image](https://user-images.githubusercontent.com/107636729/178018835-906b8ca1-eb7a-4a67-9759-a07e461cef32.png)
Ты сохраняешь в файл List< Task> а загружаешь из файла как TaskManager
Нужно изменить на JsonConvert.DeserializeObject<List< Task>>(string)
